### PR TITLE
Set runewidth.StrictEmojiNeutral = false

### PR DESCRIPTION
**Pull request by mattn**
In previous change, `runewidth.StringWidth("👁")` return always 2. But this is defined as Neutral in Unicode tr11. This should be returned as 1 in strict definition. So I added flag to return StrictEmojiNeutral to be possible to unset this.

### CODE REVIEW

**Comment by jiro4989** [comment]
```bash
$ ./width あいうえお漢字😃😁😂😅👀👄👃👁🍣（）👑abcdefgg
Char CodePoint Width
あ 12354 2
い 12356 2
う 12358 2
え 12360 2
お 12362 2
漢 28450 2
字 23383 2
😃 128515 2
😁 128513 2
😂 128514 2
😅 128517 2
👀 128064 2
👄 128068 2
👃 128067 2
👁 128065 1
🍣 127843 2
（ 65288 2
） 65289 2
👑 128081 2
a 97 1
b 98 1
c 99 1
d 100 1
e 101 1
f 102 1
g 103 1
```

**Comment by mattn** [comment]
Ooops. Could you please try last change?

**Comment by jiro4989** [comment]
```bash
$ pwd
/home/jiro4989/src/github.com/mattn/textimg/scripts/width 

$ git branch
  master
* non-strict-emoji-neutral

$ go build

$ ./width あいうえお漢字😃😁😂😅👀👄👃👁🍣（）👑abcdefg
Char CodePoint Width
あ 12354 2
い 12356 2
う 12358 2
え 12360 2
お 12362 2
漢 28450 2
字 23383 2
😃 128515 2
😁 128513 2
😂 128514 2
😅 128517 2
👀 128064 2
👄 128068 2
👃 128067 2
👁 128065 1
🍣 127843 2
（ 65288 2
） 65289 2
👑 128081 2
a 97 1
b 98 1
c 99 1
d 100 1
e 101 1
f 102 1
g 103 1
```

hmm.
Returns same result.

**Comment by mattn** [comment]
Did you try last change?

image

**Comment by jiro4989** [comment]
```bash
⟩ pwd
/home/jiro4989/src/github.com/mattn/textimg/scripts/width

⟩ git log -n 1 --oneline 
f3b4c90 (HEAD -> non-strict-emoji-neutral, origin/non-strict-emoji-neutral) ditto

⟩ tail -n 8 main.go
        args := os.Args
        fmt.Println("Char CodePoint Width")
        runewidth.DefaultCondition.StrictEmojiNeutral = false
        for _, c := range args[1] {
                text := fmt.Sprintf("%v %d %d", string(c), c, runewidth.RuneWidth(c))
                fmt.Println(text)
        }
}

⟩ go version
go version go1.16 linux/amd64

⟩ go build

⟩ ./width あいうえお漢字😃😁😂😅👀👄👃👁🍣（）👑abcdefgg
Char CodePoint Width
あ 12354 2
い 12356 2
う 12358 2
え 12360 2
お 12362 2
漢 28450 2
字 23383 2
😃 128515 2
😁 128513 2
😂 128514 2
😅 128517 2
👀 128064 2
👄 128068 2
👃 128067 2
👁 128065 1
🍣 127843 2
（ 65288 2
） 65289 2
👑 128081 2
a 97 1
b 98 1
c 99 1
d 100 1
e 101 1
f 102 1
g 103 1
```

**Comment by jiro4989** [comment]
I tried with latest your code.
But width of 👁 is 1 yet.

**Comment by mattn** [comment]
Hmm, I'm confusing. Could you please try:

```
$ cd /home/jiro4989/src/github.com/mattn/textimg/
$ go get -u -d -x ./...
$ go scripts/width
$ go build
```

**Comment by mattn** [comment]
Ah, I figure out this. Probably, you $LANG is `C` or `en_US.UTF-8`. Right?

**Comment by jiro4989** [comment]
Thank you !
I understood.

```bash
⟩ env | grep LANG
LANG=C.UTF-8

⟩LANG=ja_JP.UTF-8 ./width あいうえお漢字😃😁😂😅👀👄👃👁🍣（）👑abcdefgg
Char CodePoint Width
あ 12354 2
い 12356 2
う 12358 2
え 12360 2
お 12362 2
漢 28450 2
字 23383 2
😃 128515 2
😁 128513 2
😂 128514 2
😅 128517 2
👀 128064 2
👄 128068 2
👃 128067 2
👁 128065 2
🍣 127843 2
（ 65288 2
） 65289 2
👑 128081 2
a 97 1
b 98 1
c 99 1
d 100 1
e 101 1
f 102 1
g 103 1

```

**Comment by jiro4989** [comment]
Thank your awesome work.

LGTM 👍 

LGTM

**Review by jiro4989 — APPROVED** [review]

**Pull request merged**
